### ISSUE TITLE
ERROR: Directory 'openvsp/.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by iiwolf** [OpenVSP/OpenVSP#217]
When following  `src/python_api/README.md`, I get this error on step 4.

```bash
ERROR: Directory 'openvsp/.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

Alternatively if I do `requirements-dev.txt`:

```bash
(vsppytools) [packages] pip install -r requirements-dev.txt                 main 
Obtaining file:///home/ijw/projects/N221-004/OpenVSP/src/python_api/packages/utilities (from -r requirements-dev.txt (line 1))
  Preparing metadata (setup.py) ... done
Obtaining file:///home/ijw/projects/N221-004/OpenVSP/src/python_api/packages/degen_geom (from -r requirements-dev.txt (line 2))
  Preparing metadata (setup.py) ... done
Obtaining file:///home/ijw/projects/N221-004/OpenVSP/src/python_api/packages/openvsp (from -r requirements-dev.txt (line 3))
ERROR: file:///home/ijw/projects/N221-004/OpenVSP/src/python_api/packages/openvsp (from -r requirements-dev.txt (line 3)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

If I change `openvsp/setup.py.in` to `setup.py` it works just fine. Not familiar with .in and why it might be named that!

I'm on Ubuntu 18.04. Let me know if you'd like anymore information.

**Comment by iiwolf** [comment]
This lets the Python packages install, but then I get the same issue as listed in #212 
```bash
Traceback (most recent call last):
  File "/home/ijw/projects/N221-004/OpenVSP/src/python_api/packages/../test.py", line 4, in <module>
    import openvsp as vsp
  File "/home/ijw/projects/N221-004/OpenVSP/src/python_api/packages/openvsp/openvsp/__init__.py", line 1, in <module>
    from .vsp import *
ModuleNotFoundError: No module named 'openvsp.vsp'
```

**Comment by iiwolf** [comment]
This was as a result of trying to install from the repo **source** directory instead of the **install** location. e.g. 

```/home/usr/openvsp/repo/src/python_api/packages```

Instead the install location:

```/usr/local/python```

In hindsight this makes perfect sense, but I don't believe it's clear in the documentation.
