### ISSUE TITLE
Segfault in 'VSPAERO' after 'Wave Drag' 

### ISSUE THREAD

**Issue by smagellan** [OpenVSP/OpenVSP#223]
Debian testing, OpenVSP 3.26.1
0) Download model: http://hangar.openvsp.org/vspfiles/416/download? to ~/Downloads/Myjet.vsp3
1) Run vsp under catchsegv or gdb:
```
catchsegv ./vsp ~/Downloads/Myjet.vsp3
```
2) Run  'Analysis -> Wave Drag' with default params
3) Run  'Analysis -> VSPAERO'
4) Segfault:
<details>
  <summary>Release version catchsegv backtrace</summary>

```
./vsp(removeghosts+0x62)[0x55a6e4560c82]
./vsp(divconqdelaunay+0x15d)[0x55a6e4560e8d]
./vsp(delaunay+0x34)[0x55a6e4562774]
./vsp(triangle_mesh_create+0x7e)[0x55a6e455934e]
./vsp(_ZN4TTri16TriangulateSplitEi+0x70b)[0x55a6e3f0e67b]
./vsp(_ZN4TTri8SplitTriEv+0x15f2)[0x55a6e3f107a2]
./vsp(_ZN5TMesh5SplitEv+0x2e)[0x55a6e3f06e1e]
./vsp(_ZN8MeshGeom13IntersectTrimERSt6vectorI9DegenGeomSaIS1_EEbii+0x829)[0x55a6e3e4b599]
./vsp(_ZN7Vehicle15CreateDegenGeomEi+0x667)[0x55a6e3f3b037]
./vsp(_ZN19VSPAEROMgrSingleton15ComputeGeometryB5cxx11Ev+0x216)[0x55a6e4019676]
./vsp(_ZN13VSPAEROScreen17GuiDeviceCallBackEP9GuiDevice+0x359)[0x55a6e3c09809]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_ZN9Fl_Widget11do_callbackEPS_Pv+0x41)[0x7f889eb89c21]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_ZN9Fl_Button6handleEi+0x258)[0x7f889eb37e38]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(+0x44993)[0x7f889eb2f993]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_ZN2Fl7handle_EiP9Fl_Window+0x21e)[0x7f889eb316be]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_Z9fl_handleRK7_XEvent+0x6ea)[0x7f889eb9119a]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(+0xa78a2)[0x7f889eb928a2]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_Z7fl_waitd+0x2b2)[0x7f889eb92c02]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_ZN2Fl4waitEd+0x139)[0x7f889eb31139]
/usr/lib/x86_64-linux-gnu/libfltk.so.1.3(_ZN2Fl3runEv+0x21)[0x7f889eb31201]
./vsp(main+0x4f)[0x55a6e3b4570f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xcd)[0x7f889e46c7ed]
./vsp(_start+0x2a)[0x55a6e3b4e7ba]
```
</details>

<details>
  <summary>Debug version gdb backtrace</summary>

```
#0  0x0000555557188b11 in removeghosts (m=0x555562995690, b=0x555562995590, startghost=0x7fffffffa310) at /home/vladimir/projects/OpenVSP/buildlibs/TRIANGLE-prefix/src/TRIANGLE/src/Triangle/triangle.c:4455
#1  0x0000555557188ed7 in divconqdelaunay (m=0x555562995690, b=0x555562995590) at /home/vladimir/projects/OpenVSP/buildlibs/TRIANGLE-prefix/src/TRIANGLE/src/Triangle/triangle.c:4536
#2  0x000055555718bba7 in delaunay (m=0x555562995690, b=0x555562995590) at /home/vladimir/projects/OpenVSP/buildlibs/TRIANGLE-prefix/src/TRIANGLE/src/Triangle/triangle.c:5384
#3  0x000055555717a9d1 in triangle_mesh_create (ctx=0x5555610ab180, in=0x7fffffffa530) at /home/vladimir/projects/OpenVSP/buildlibs/TRIANGLE-prefix/src/TRIANGLE/src/Triangle/triangle_api.c:209
#4  0x00005555568dcbd8 in TTri::TriangulateSplit (this=0x55555d9dfda0, flattenAxis=0) at /home/vladimir/projects/OpenVSP/repo/src/geom_core/TMesh.cpp:2110
#5  0x00005555568dbc8d in TTri::SplitTri (this=0x55555d9dfda0) at /home/vladimir/projects/OpenVSP/repo/src/geom_core/TMesh.cpp:1921
#6  0x00005555568d5cbf in TMesh::Split (this=0x55555eadd270) at /home/vladimir/projects/OpenVSP/repo/src/geom_core/TMesh.cpp:803
#7  0x00005555567cd393 in MeshGeom::IntersectTrim (this=0x55555e2a2180, degenGeom=std::vector of length 33, capacity 64 = {...}, degen=true, halfFlag=0, intSubsFlag=0)
    at /home/vladimir/projects/OpenVSP/repo/src/geom_core/MeshGeom.cpp:1981
#8  0x0000555556923671 in Vehicle::CreateDegenGeom (this=0x5555581d4090, set=0) at /home/vladimir/projects/OpenVSP/repo/src/geom_core/Vehicle.cpp:5369
#9  0x0000555556a320d2 in VSPAEROMgrSingleton::ComputeGeometry[abi:cxx11]() (this=0x55555811dac0 <VSPAEROMgrSingleton::getInstance()::instance>)
    at /home/vladimir/projects/OpenVSP/repo/src/geom_core/VSPAEROMgr.cpp:1156
#10 0x00005555564b3ff0 in VSPAEROScreen::GuiDeviceCallBack (this=0x55555c99ec40, device=0x55555c9a2bf8) at /home/vladimir/projects/OpenVSP/repo/src/gui_and_draw/VSPAEROScreen.cpp:989
#11 0x000055555654ba15 in TriggerButton::DeviceCB (this=0x55555c9a2bf8, w=0x55555c9ab0e0) at /home/vladimir/projects/OpenVSP/repo/src/gui_and_draw/GuiDevice.cpp:1557
#12 0x0000555556556d49 in GuiDevice::StaticDeviceCB (w=0x55555c9ab0e0, data=0x55555c9a2bf8) at /home/vladimir/projects/OpenVSP/repo/src/gui_and_draw/GuiDevice.h:164
#13 0x00007ffff7d15c21 in Fl_Widget::do_callback(Fl_Widget*, void*) () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#14 0x00007ffff7cc3e38 in Fl_Button::handle(int) () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#15 0x00007ffff7cbb993 in ?? () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#16 0x00007ffff7cbd6be in Fl::handle_(int, Fl_Window*) () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#17 0x00007ffff7d1d19a in fl_handle(_XEvent const&) () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#18 0x00007ffff7d1e8a2 in ?? () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#19 0x00007ffff7d1ec02 in fl_wait(double) () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#20 0x00007ffff7cbd139 in Fl::wait(double) () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#21 0x00007ffff7cbd201 in Fl::run() () from /usr/lib/x86_64-linux-gnu/libfltk.so.1.3
#22 0x00005555563f215e in GuiInterface::StartGui (this=0x5555581168a0 <GuiInterface::getInstance()::instance>) at /home/vladimir/projects/OpenVSP/repo/src/geom_api/GuiInterface.cpp:49
#23 0x00005555563f1e01 in main (argc=2, argv=0x7fffffffdf68) at /home/vladimir/projects/OpenVSP/repo/src/vsp/main.cpp:222
```
</details>

**Comment by ramcdona** [comment]
When you run wave drag, it deposits a MeshGeom with all of the slices used in the analysis on the Geom Tree.

This MeshGeom needs to be deleted before running VSPAERO.

If you have general questions about running OpenVSP, the best place to ask them is on the OpenVSP Google Group.
